/**
 * The vocabulary: the primitives every report is composed from.
 *
 * This replaces a 764-row database of pre-written combinations
 * ("Mars in Scorpio in the 8th" as one blob) with the ideas those blobs were
 * mechanically built from: what each body does, how each sign does it, where
 * each house puts it, what each aspect type is, and the structural concepts
 * that describe a chart as a whole. Composition happens at assembly time.
 *
 * The doctrine follows the classical sources the product is grounded in
 * (Demetra George; Chris Brennan; Avelar & Ribeiro), in our own words. Entries
 * are descriptive, third person, and never explain method: the reader-facing
 * prompts forbid method talk, so the vocabulary must not smuggle it in. The
 * words are everyday words, one idea per sentence (ADR-257), because every
 * system prompt carries the block and a writer echoes the register it is shown.
 *
 * Every entry has a `short` (one sentence, used for the wheel cards and the
 * chart brief) and a `full` (40–80 words, used in the shared system block).
 * The `full` entries and the aspects' four lines are written by hand: edit
 * them in place. `pnpm generate:vocabulary` regenerates the shorts from the
 * generation prompts in scripts/src/generate-vocabulary.ts and keeps the rest
 * as written, so a regeneration never brings the textbook register back.
 *
 * Provenance: this first version was drafted by Claude in September 2026 and
 * committed so the pipeline is complete end to end. It has not yet been
 * regenerated by the script.
 */

export interface VocabEntry {
  /** One sentence. Wheel cards, brief lines. */
  short: string;
  /** 40–80 words. Shared system block. */
  full: string;
}

export interface AspectEntry {
  short: string;
  /** What the relationship between the two functions is. */
  dynamic: string;
  /** How it shows when it is working. */
  inFlow: string;
  /** How it shows under pressure. */
  underStress: string;
  /** What working with it looks like. */
  growth: string;
}

export const BODIES = [
  "sun", "moon", "mercury", "venus", "mars", "jupiter", "saturn",
  "uranus", "neptune", "pluto", "chiron", "north_node", "south_node",
] as const;
export type Body = (typeof BODIES)[number];

export const SIGNS = [
  "aries", "taurus", "gemini", "cancer", "leo", "virgo",
  "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
] as const;
export type SignName = (typeof SIGNS)[number];

export const ASPECTS = ["conjunction", "sextile", "square", "trine", "opposition"] as const;
export type AspectName = (typeof ASPECTS)[number];

export const BODY_LABELS: Record<Body, string> = {
  sun: "Sun", moon: "Moon", mercury: "Mercury", venus: "Venus", mars: "Mars",
  jupiter: "Jupiter", saturn: "Saturn", uranus: "Uranus", neptune: "Neptune",
  pluto: "Pluto", chiron: "Chiron", north_node: "North Node", south_node: "South Node",
};

// ---------------------------------------------------------------------------
// Bodies: the function
// ---------------------------------------------------------------------------

export const BODY: Record<Body, VocabEntry> = {
  sun: {
    short: "The Sun is the centre of identity and the sense of what one is for.",
    full: "The Sun is a person's sense of self: who they are, what drives them, and what they want their life to be about. It shows what they build their life around. It shows where they feel most like themselves and want to be seen for it. In a day chart it leads. In a night chart the Moon leads instead. The Sun still gives a sense of direction.",
  },
  moon: {
    short: "The Moon is the body, the habits, and what makes someone feel safe.",
    full: "The Moon is the body and its needs. It shows what calms a person down and what they reach for under stress. It sets the rhythm of their days and the feelings that come before they think. It shows how they look after themselves and others, and what they need in place to cope. In a night chart it leads.",
  },
  mercury: {
    short: "Mercury is how a person thinks, learns, decides and makes themselves understood.",
    full: "Mercury is how a person thinks and talks: noticing, language, reasoning, learning and passing on information. It shows how someone takes in the world, explains themselves and decides. It shows what kind of thinking comes easily. It is neither a day planet nor a night planet. It takes on the nature of the planets it sits with.",
  },
  venus: {
    short: "Venus is attraction, pleasure, taste, and the capacity to draw people in.",
    full: "Venus is attraction and making peace. It shows what a person finds beautiful, what they enjoy, and how they draw people closer. It covers taste, affection, cooperation and the pleasures that make life worth the effort. It is the helpful planet of the night side, kinder and more reliable in a night chart.",
  },
  mars: {
    short: "Mars is drive, assertion, and the capacity to cut through and go after something.",
    full: "Mars is how a person pushes for what they want: effort, courage, competition, anger, and the ability to say no and walk away. It shows how they go after things, how they fight and how they handle conflict. It is the hard planet of the night side. It does more good by night. In a day chart it is harsher and costs more.",
  },
  jupiter: {
    short: "Jupiter is expansion, confidence, generosity, and the sense that more is possible.",
    full: "Jupiter is growth and confidence: generosity, meaning, opportunity and the ability to say yes. It shows where a person finds plenty, what they trust, how they grow and where they take on too much. It is the helpful planet of the day side. It does the most good in a day chart and is a little less steady by night.",
  },
  saturn: {
    short: "Saturn is structure, limit, duration, and the discipline that makes things last.",
    full: "Saturn is limits and staying power: structure, responsibility, time, boundaries and the seriousness that makes work last. It shows where a person is disciplined, where they are afraid, and what they build slowly and refuse to rush. It is the hard planet of the day side and does useful work by day. In a night chart it is harsher and brings more fear.",
  },
  uranus: {
    short: "Uranus is disruption, independence, and the sudden break from what was expected.",
    full: "Uranus is sudden change and independence. It covers invention, surprise and refusing to fit in. It shows where a person breaks the pattern and where they need freedom. It shows where life tends to change without warning. It rules no sign and has no dignity. It is read by the house it sits in, never as a ruler.",
  },
  neptune: {
    short: "Neptune is dissolution, longing, imagination, and the blurring of hard edges.",
    full: "Neptune is imagination and longing. It covers ideals, compassion, confusion and the wish for something beyond everyday life. It shows where a person is most sensitive and most inspired. It also shows where they are most easily fooled. It rules no sign and has no dignity. It adds to the house it sits in and rules nothing.",
  },
  pluto: {
    short: "Pluto is intensity, power, and transformation through what cannot be avoided.",
    full: "Pluto is intensity and deep change. It covers power, compulsion, endings and being changed by what a person cannot control. It shows where someone meets their own intensity. It shows where life asks them to face something fully. It rules no sign and has no dignity. It adds to the house it sits in and rules nothing.",
  },
  chiron: {
    short: "Chiron marks a wound that becomes a source of skill and understanding for others.",
    full: "Chiron marks a lasting hurt that never fully goes away. Over time it becomes a source of skill and care for others. It shows where a person is good at helping with the very thing they struggle with themselves. It is a modern point. It rules nothing and has no dignity. It is read by its house.",
  },
  north_node: {
    short: "The North Node is the direction of growth: unfamiliar, uncomfortable, and worth it.",
    full: "The North Node marks the direction a life is pulled toward: skills that are still weak, situations that feel new, and areas where effort leads to growth. It rarely feels natural. It is read as a direction, not a placement, and always together with the South Node. It is not a planet.",
  },
  south_node: {
    short: "The South Node is the default: what comes easily and what gets overused.",
    full: "The South Node marks what a person falls back on: the skills they arrived with, the habits they return to, and the comfort zone that holds them back when they never leave it. It shows what comes easily and what gets overused. It is read with the North Node as one axis. It is not a planet.",
  },
};

// ---------------------------------------------------------------------------
// Signs: the style
// ---------------------------------------------------------------------------

/** brief.ts reads a rising sign's `full`: sentences 2 and 3 are it at its best, and "Under strain it becomes" opens the last. */
export const SIGN: Record<SignName, VocabEntry> = {
  aries: {
    short: "Aries acts first, directly and fast, and sorts things out afterward.",
    full: "Aries is a cardinal fire sign, ruled by Mars, with the Sun exalted in it. Anything placed here moves first and moves fast. It would rather act and fix things later than wait. It is honest, brave, competitive and blunt. Under strain it becomes rash, quick to fight, or unable to finish what it started.",
  },
  taurus: {
    short: "Taurus is steady, sensual, slow to start and slower to stop.",
    full: "Taurus is a fixed earth sign, ruled by Venus, with the Moon exalted in it. Anything placed here wants life to be steady and comfortable. It takes its time and likes results it can see and touch. It is patient, loyal, practical and attached to what it has. Under strain it becomes stubborn, possessive, or unwilling to change even when it should.",
  },
  gemini: {
    short: "Gemini is quick, curious, verbal, and interested in everything at once.",
    full: "Gemini is a mutable air sign, ruled by Mercury. Anything placed here is curious and quick with words. It wants to know things, talk about them and link one idea to the next. It is clever, friendly, adaptable and quick to see another angle. Under strain it becomes scattered, restless, vague, or unable to stick to one plan.",
  },
  cancer: {
    short: "Cancer protects, remembers, and holds close what it cares about.",
    full: "Cancer is a cardinal water sign, ruled by the Moon, with Jupiter exalted in it. Anything placed here protects and cares for people. It is shaped by memory and by where it belongs. It is loyal, caring and good at sensing what others need. Under strain it becomes defensive, moody, clingy, or unable to let go.",
  },
  leo: {
    short: "Leo is warm, proud, generous, and needs to be seen doing it.",
    full: "Leo is a fixed fire sign, ruled by the Sun. Anything placed here wants to stand out and to make things. It wants credit for what it does. It is warm, loyal, open and confident. It leads by example and gives generously. Under strain it becomes proud, demanding, dramatic, or unable to take criticism without feeling hurt.",
  },
  virgo: {
    short: "Virgo notices what is wrong and quietly fixes it.",
    full: "Virgo is a mutable earth sign, ruled by Mercury, which is also exalted in it. Anything placed here notices details and wants things to work properly. It improves things step by step, with a method. It is skilled, careful and useful. It likes to help in practical ways. Under strain it becomes critical, anxious, perfectionist, or lost in small details.",
  },
  libra: {
    short: "Libra weighs, balances, and seeks fairness and the other person's view.",
    full: "Libra is a cardinal air sign, ruled by Venus, with Saturn exalted in it. Anything placed here looks for balance, fairness and partnership. It thinks about the other side and values agreement. It is tactful, fair and has good taste. Under strain it becomes indecisive, afraid of conflict, dependent on approval, or unable to say what it wants.",
  },
  scorpio: {
    short: "Scorpio goes deep, holds on, and does not do anything by halves.",
    full: "Scorpio is a fixed water sign, ruled by Mars. Anything placed here is intense, private and all or nothing. It wants to know what is really going on. It holds on hard and would rather change completely than adjust a little. It is loyal, perceptive and tough. Under strain it becomes controlling, suspicious, vengeful, or unable to let go.",
  },
  sagittarius: {
    short: "Sagittarius aims far, believes big, and says what it thinks.",
    full: "Sagittarius is a mutable fire sign, ruled by Jupiter. Anything placed here looks for meaning, distance and freedom. It explores, teaches and says what it thinks. It is hopeful, generous and drawn to big ideas. It likes to travel and to learn. Under strain it becomes preachy, careless with details, restless, or unable to keep its promises.",
  },
  capricorn: {
    short: "Capricorn is disciplined, ambitious, and plays the long game.",
    full: "Capricorn is a cardinal earth sign, ruled by Saturn, with Mars exalted in it. Anything placed here is serious and plans for the long run. It takes responsibility and works its way up slowly. It is capable, reliable and has a dry sense of humour. Under strain it becomes cold, rigid, overworked, or unable to rest until it is too late.",
  },
  aquarius: {
    short: "Aquarius stands apart, thinks in systems, and cares about the group.",
    full: "Aquarius is a fixed air sign, ruled by Saturn. Anything placed here stands a little apart and lives by its principles. It thinks in patterns and systems. It cares about the group, values independence and is loyal to ideas and to friends. Under strain it becomes distant, contrary, rigid in its views, or unable to be close in person.",
  },
  pisces: {
    short: "Pisces feels everything, blurs boundaries, and gives more than it keeps.",
    full: "Pisces is a mutable water sign, ruled by Jupiter, with Venus exalted in it. Anything placed here is open, kind and imaginative. It takes on the moods of the people around it. It finds it hard to keep clear limits. It is gentle, generous, intuitive and forgiving. Under strain it becomes escapist, vague, overwhelmed, or unable to say no.",
  },
};

// ---------------------------------------------------------------------------
// Houses: the domain (whole-sign)
// ---------------------------------------------------------------------------

// MB-87 provisional
/**
 * The page's one word per house (ADR-98), as the web prints it beside every
 * house number. A short opens with it so the planet rows a report stores and
 * the page name a house alike.
 */
export const HOUSE_WORDS = [
  "Self", "Money", "Mind", "Home", "Play", "Work",
  "Partnership", "Depth", "Belief", "Career", "Friends", "Solitude",
] as const;

export const HOUSE: Record<number, VocabEntry> = {
  1: { short: "The 1st is self: the body, presence, and how one meets the world.", full: "The 1st house is the person themselves: the body, the temperament, and how others first see them. It holds the Ascendant. Its ruler is the chart ruler. It is angular and strong. What is here is clearly part of who the person is. Other people notice it first." },
  2: { short: "The 2nd is money: resources, possessions, and what one values and keeps.", full: "The 2nd house is money and the things a person owns. It covers income, property, what they earn and keep, and whether they feel they have enough. It also shows what they value and how they judge worth. It is succedent. What is here shows how money comes in and how it is handled." },
  3: { short: "The 3rd is mind: daily talk, learning, siblings, neighbours, and the near world.", full: "The 3rd house is daily life close to home. It covers brothers and sisters, neighbours, short trips, everyday talk, early school and the ordinary chats of a day. The Moon has her joy here. It is cadent. What is here shows how a person handles what is local, what is routine, and what is said out loud." },
  4: { short: "The 4th is home: family, roots, and what a person carries from their origins.", full: "The 4th house is home and family. It covers parents, family history, land and private life. It is the bottom of the chart and the most private place in it. It is angular. What is here shows where a person comes from. It also shows what they need in order to feel settled." },
  5: { short: "The 5th is play: pleasure, creativity, children, and what one does for its own sake.", full: "The 5th house is fun and making things. It covers play, romance, children, art, performing, and whatever a person does just for the joy of it. Venus has her joy here. It is succedent. What is here shows how a person enjoys themselves, what they make, and how they treat pleasure." },
  6: { short: "The 6th is work: routine, health, and what must be maintained.", full: "The 6th house is daily work and upkeep. It covers jobs, routines, illness, service, and the plain effort that keeps a life running. Mars has his joy here. It is cadent. The tradition counts it as a hard house. What is here shows how a person handles duties, repetition, and a body under strain." },
  7: { short: "The 7th is partnership: the other person, spouses, open rivals, and one-to-one bonds.", full: "The 7th house is the other person. It covers marriage, partners, contracts and open rivals. It holds the Descendant, opposite the self. It is angular. What is here, and where its ruler goes, shows who a person commits to. It also shows how their partnerships go." },
  8: { short: "The 8th is depth: shared resources, loss, inheritance, and what is not one's own.", full: "The 8th house is what belongs to other people and what is lost. It covers shared money, inheritance, debt, death, and the fear that comes with them. The tradition counts it as a hard house. It is succedent. What is here shows how a person handles shared money, endings, and what they cannot control." },
  9: { short: "The 9th is belief: the far world, higher learning, travel, and meaning.", full: "The 9th house is what is far away and bigger than daily life. It covers beliefs, religion, higher education, long trips, foreign places and the search for meaning. The Sun has his joy here. It is cadent but respected. What is here shows what a person believes, how they study in depth, and where they look for the truth." },
  10: { short: "The 10th is career: vocation, reputation, and what one is known for doing.", full: "The 10th house is a person's public life. It covers career, reputation, authority, success, and what they are seen to do in the world. It holds the Midheaven. It is angular and strong. What is here, and where its ruler goes, shows what a working life looks like. It also shows how recognition comes." },
  11: { short: "The 11th is friends: allies, groups, and hopes shared with others.", full: "The 11th house is friends and allies. The tradition calls it the good spirit. It covers groups, supporters, and the hopes and help that come through other people. Jupiter has his joy here. It is succedent and lucky. What is here shows how a person gets help, who they belong with, and how they work with others toward shared goals." },
  12: { short: "The 12th is solitude: what is hidden, sorrow, secrets, and self-undoing.", full: "The 12th house is what is hidden. It covers time alone, retreat, being shut away, hidden enemies, private sadness, and the ways a person works against themselves. Saturn has his joy here. It is cadent. The tradition counts it as the hardest house. What is here works out of sight. It is often only understood later." },
};

// ---------------------------------------------------------------------------
// Aspects: the relationship
// ---------------------------------------------------------------------------

export const ASPECT: Record<AspectName, AspectEntry> = {
  conjunction: {
    short: "A conjunction fuses two functions so neither operates without the other.",
    dynamic: "Two planets sit in the same place and act as one. Neither can be used without the other. Their natures blend, for better or worse, depending on how well they get along.",
    inFlow: "The two work as one combined strength.",
    underStress: "The trouble with one affects the other. Neither is easy to use alone.",
    growth: "Learning which of the two is acting, and giving each its turn.",
  },
  sextile: {
    short: "A sextile is an easy, workable connection that rewards a little effort.",
    dynamic: "Two planets in signs that get along support each other when asked. The link is friendly and useful but not automatic. It is a chance, not a given.",
    inFlow: "The two cooperate easily and get practical results with a little effort.",
    underStress: "Unused. The help is there but nobody takes it.",
    growth: "Using the link on purpose instead of waiting for it to act by itself.",
  },
  square: {
    short: "A square is friction between two functions that forces something to develop.",
    dynamic: "Two planets in signs that share a mode but not an element push against each other. Neither gives way easily. The pressure is constant. This is where effort is forced and skill is built.",
    inFlow: "Skill earned the hard way. The tension now pushes the person forward.",
    underStress: "Repeated conflict, frustration and the feeling of being pulled two ways at once.",
    growth: "Accepting that the tension will stay and building something from it instead of trying to make it go away.",
  },
  trine: {
    short: "A trine is a natural ease between two functions that asks nothing.",
    dynamic: "Two planets in signs of the same element work together without effort. What they do together comes easily. It often comes so easily that it goes unnoticed and undervalued.",
    inFlow: "Natural talent. The two work together easily and reliably.",
    underStress: "Taking it for granted. The gift is left undeveloped or used as an excuse to avoid harder things.",
    growth: "Treating the ease as something to invest, not a comfort to rest in.",
  },
  opposition: {
    short: "An opposition sets two functions face to face, each seeing what the other lacks.",
    dynamic: "Two planets in opposite signs pull in opposite directions. Each can see the other clearly. The tension often shows up between the person and someone else. It can also show up as a swing between two extremes.",
    inFlow: "Balance and perspective. Each side keeps the other in check. The person can hold both.",
    underStress: "Taking sides. The person sides with one end and meets the other in someone else, usually as conflict.",
    growth: "Owning both ends instead of putting one on someone else, and finding the middle ground.",
  },
};

// ---------------------------------------------------------------------------
// Structural concepts
// ---------------------------------------------------------------------------

export const STRUCTURE: Record<string, VocabEntry> = {
  sect_day: { short: "A day chart: the Sun leads, Jupiter and Saturn help, Mars costs.", full: "In a day chart the Sun leads. The chart runs on identity, purpose and direction. Of the two helpful planets, Jupiter helps more. Saturn does steady, useful work. Mars is contrary to sect: out of step with the chart. The person's drive is real but tends to push too hard and cost them something." },
  sect_night: { short: "A night chart: the Moon leads, Venus and Mars help, Saturn costs.", full: "In a night chart the Moon leads. The chart runs on needs, safety, instinct and relationships. Of the two helpful planets, Venus helps more. Mars does steady, useful work. Saturn is contrary to sect: out of step with the chart. The person's discipline is real but tends toward coldness, fear and a low mood." },
  chart_ruler: { short: "The chart ruler is the planet that rules the rising sign and stands for the person.", full: "The planet that rules the rising sign is the chart ruler. It stands for the person more directly than any other planet. It shows their health, their drive and where their life is heading. Its sign, house, dignity and sect condition describe the person's own condition." },
  domicile: { short: "A planet in domicile is at home and does its work fully and on its own terms.", full: "A planet in one of its own signs is in domicile. It has everything it needs and acts with authority. It does not depend on anyone else. What it stands for is strong and reliable in this person's life. It works on the person's own terms." },
  exaltation: { short: "A planet in exaltation is honoured and elevated, sometimes beyond its means.", full: "A planet in its exaltation sign is raised up and treated well. It can do great things. Sometimes it has more confidence than substance. What it stands for is prominent in the person's life. It tends to be idealised." },
  detriment: { short: "A planet in detriment is out of place and works hard for uneven results.", full: "A planet in the sign opposite its own is in detriment. It works in a style that does not suit it. It lacks its usual support. What it stands for is real and often strong. It comes through difficulty and does not come naturally." },
  fall: { short: "A planet in fall is undervalued and tends to be doubted, including by its owner.", full: "A planet in the sign opposite its exaltation is in fall. It is overlooked and underestimated. It is easily made to feel small. What it stands for is often what the person doubts most in themselves. It is also what most needs deliberate support." },
  peregrine: { short: "A peregrine planet has no dignity here and takes its character from what surrounds it.", full: "A planet with no dignity in its sign is peregrine. It is not at home, not honoured and not opposed. It has no fixed standing. It relies on its house, its aspects and its ruler for support. What it stands for is adaptable but unsteady." },
  angular: { short: "An angular planet is prominent, visible, and shapes the life directly.", full: "A planet in the 1st, 4th, 7th or 10th house is angular. It sits at one of the four main points of the chart. It is prominent and active. What it stands for shows up clearly in the person's life. It is hard to miss." },
  succedent: { short: "A succedent planet is steady, resourced, and follows through.", full: "A planet in the 2nd, 5th, 8th or 11th house is succedent. It is stable and well supported. It works well. It is less visible than an angular planet. What it stands for builds over time and lasts." },
  cadent: { short: "A cadent planet is in the background, working in preparation or in private.", full: "A planet in the 3rd, 6th, 9th or 12th house is cadent. It sits away from the four main points. It is quieter and works in the background, in thought or out of sight. What it stands for is present but not prominent. It may need to be looked for." },
  stellium: { short: "A stellium concentrates the chart into one place that dominates everything else.", full: "Three or more planets in one sign or house form a stellium. That part of the chart gets most of the attention. Whatever the sign and house describe becomes the person's main concern. Other areas of life stay quieter by comparison." },
  retrograde: { short: "A retrograde planet works inward and on its own schedule.", full: "A retrograde planet seems to move backward in the sky. What it stands for is turned inward. It is rethought, slower to show and often worked out in private first. It matures on the person's own timetable, not the expected one." },
  empty_house: { short: "An empty house is read through its ruler, not dismissed.", full: "A house with no planets in it is still active. Its matters are read through its ruling planet. Where that ruler sits, and what condition it is in, shows where and how the matters of the empty house happen." },
  nodal_axis: { short: "The nodal axis runs from default competence toward unfamiliar growth.", full: "The nodes form one axis. The South Node marks what is easy, practised and overused. The North Node marks what is still weak and uncomfortable, and where effort leads to growth. The signs and houses at each end name the areas involved." },
  lot_of_fortune: { short: "The Lot of Fortune is where material circumstance and the body's fortune concentrate.", full: "The Lot of Fortune is a calculated point. It marks income, the body and a person's material situation. It is about what comes to a person from the world, not what they make happen. Its house shows where luck, good or bad, tends to arrive." },
  lot_of_spirit: { short: "The Lot of Spirit is where agency, intention, and vocation concentrate.", full: "The Lot of Spirit is the partner of the Lot of Fortune. It is a calculated point. It marks choice, intention and what a person does rather than what happens to them. Its house shows where their drive and the work they feel drawn to are most active." },
  element_fire: { short: "Fire is initiative, heat, confidence, and the will to act.", full: "Fire signs carry initiative, enthusiasm, courage and self-belief. A chart with a lot of fire acts first and gets excited fast. A chart with little fire may lack drive or confidence. It has to build them on purpose." },
  element_earth: { short: "Earth is practicality, patience, the body, and what can be touched.", full: "Earth signs carry practical sense, patience, staying power and attention to the physical world. A chart with a lot of earth is steady and slow. A chart with little earth may struggle with money, routine or the body." },
  element_air: { short: "Air is thought, language, connection, and distance from feeling.", full: "Air signs carry ideas, talk, social ease and perspective. A chart with a lot of air thinks and talks a lot. It can keep its feelings at a distance. A chart with little air may find it hard to explain itself or to see other points of view." },
  element_water: { short: "Water is feeling, memory, sensitivity, and the pull of what is unspoken.", full: "Water signs carry feeling, intuition, memory and openness. A chart with a lot of water feels everything and is affected by the mood around it. A chart with little water may lose touch with feelings or find it hard to understand others." },
  modality_cardinal: { short: "Cardinal signs begin things.", full: "Cardinal signs start things. They begin, lead and push forward. A chart with a lot of cardinal signs starts a great deal and may not finish. A chart with few may wait for others to start." },
  modality_fixed: { short: "Fixed signs sustain things.", full: "Fixed signs keep things going. They hold on, build up and resist change. A chart with a lot of fixed signs is stable and stubborn. A chart with few may not follow through or keep to a decision." },
  modality_mutable: { short: "Mutable signs adapt and finish things.", full: "Mutable signs adapt and finish things. They adjust, spread out and complete. A chart with a lot of mutable signs is flexible and scattered. A chart with few may struggle to adapt when things change." },
  shape_bundle: { short: "A bundle chart concentrates everything within a third of the wheel.", full: "All the planets sit within about a third of the wheel. The life is focused and specialised. The person cares about a narrow set of things. Much of the wheel stays quiet. What lies in the occupied third shapes everything else." },
  shape_bowl: { short: "A bowl chart holds everything in one half and looks across at the empty half.", full: "All the planets sit within one half of the wheel. The person is self-contained. They look toward the empty half. They often feel something is missing there and work toward it. The leading planet of the bowl sets the direction of that effort." },
  shape_bucket: { short: "A bucket chart has one planet standing apart from the rest, and that planet leads.", full: "All the planets sit in one half of the wheel except one, which stands alone as the handle. That single planet becomes the focus and the outlet for everything else. It matters more than usual. The person directs the rest of the chart through it." },
  shape_locomotive: { short: "A locomotive chart leaves one third empty and is driven by the planet leading the rest.", full: "The planets spread across two thirds of the wheel, with one third empty. The person is driven and has a sense of something to get done. The planet that leads the group, counted clockwise, sets the pace. The empty third names what they feel is missing." },
  shape_seesaw: { short: "A seesaw chart splits into two opposing groups and lives in the tension between them.", full: "The planets form two groups roughly opposite each other. Life moves back and forth between two sets of concerns. The person does best when they keep both in view at once. Other people often bring out the other side." },
  shape_splash: { short: "A splash chart spreads everything evenly, with wide interests and little concentration.", full: "The planets are spread around the whole wheel with no single cluster. The person has wide interests and adapts to many kinds of situation. They can lose focus by spreading their effort too thin. No one area dominates. The strongest single placements and the chart ruler count for more than usual." },
  shape_splay: { short: "A splay chart clusters in several separate places, each a distinct centre of interest.", full: "The planets gather in several separate clusters with clear gaps between them. The person is independent and hard to label. Their life is organised around a few strong interests that do not always connect. Each cluster is read as its own concern." },
};

/** Every full entry, rendered once as the static vocabulary block for the system prompt. */
export function renderVocabularyBlock(): string {
  // MB-92 provisional: reports echoed entries as sentences ("The Moon is the body…"), so the block is introduced as doctrine.
  const lines: string[] = ["VOCABULARY (doctrine for reading a chart, never lines to repeat: put what an entry means into your own plain words).", ""];
  lines.push("Bodies (what each does):");
  for (const b of BODIES) lines.push(`- ${BODY_LABELS[b]}: ${BODY[b].full}`);
  lines.push("", "Signs (how it does it):");
  for (const s of SIGNS) lines.push(`- ${cap(s)}: ${SIGN[s].full}`);
  lines.push("", "Houses (where it plays out, whole-sign):");
  for (let h = 1; h <= 12; h++) lines.push(`- ${ordinal(h)}: ${HOUSE[h].full}`);
  lines.push("", "Aspects (how two functions relate):");
  for (const a of ASPECTS) {
    const e = ASPECT[a];
    lines.push(`- ${cap(a)}: ${e.dynamic} Working: ${e.inFlow} Under pressure: ${e.underStress} Growth: ${e.growth}`);
  }
  lines.push("", "Structure:");
  for (const [k, e] of Object.entries(STRUCTURE)) lines.push(`- ${k}: ${e.full}`);
  return lines.join("\n");
}

export function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return `${n}${s[(v - 20) % 10] ?? s[v] ?? s[0]}`;
}
