/**
 * The on-tap scene against a memory store: both refusals, one write per
 * report, chapter and index, the stored text served after, the usage on the
 * meta (ADR-72, MB-64). The model is the fake; the report is generated by
 * the pipeline test's canned replies.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { chartFromFixture } from "./testFixtures.js";
import { cannedNatalReplies, installFakeModel, type FakeRequest } from "./testModel.js";

const { generateInterpretation } = await import("./aiInterpretation.js");
const { generatePairInterpretation } = await import("./pairInterpretation.js");
const { buildPairBrief } = await import("./pairBrief.js");
const { pairReplies } = await import("./testPair.js");
const { checkSceneRequest, writeScene, SceneRequestError } = await import("./pairScene.js");
const { MODELS } = await import("./models.js");
type SceneStore = import("./pairScene.js").SceneStore;
type PairInterpretation = import("./pairInterpretation.js").PairInterpretation;

const fake = installFakeModel(cannedNatalReplies({ drawn: true, sunSign: "scorpio", sunHouse: 11 }));
const curieReport = await generateInterpretation(chartFromFixture("marie-curie"), "Marie Curie");
fake.replies = cannedNatalReplies({ drawn: true, sunSign: "aquarius", sunHouse: 3, sect: "night" });
const winfreyReport = await generateInterpretation(chartFromFixture("oprah-winfrey"), "Oprah Winfrey");

const input = {
  lens: "partners" as const,
  at: new Date("2026-09-21T00:00:00Z"),
  a: { name: "Marie Curie", birthDate: "1867-11-07", chart: chartFromFixture("marie-curie"), interpretation: curieReport },
  b: { name: "Oprah Winfrey", birthDate: "1954-01-29", chart: chartFromFixture("oprah-winfrey"), interpretation: winfreyReport },
};
fake.replies = pairReplies(buildPairBrief(input));
const report = await generatePairInterpretation(input);

function memoryStore(initial: PairInterpretation) {
  const state = { interpretation: initial, saves: 0 };
  const store: SceneStore = {
    async load() { return { interpretation: state.interpretation, lens: "partners", label: null, parent: null, a: input.a, b: input.b }; },
    async save(_id, interpretation) { state.saves += 1; state.interpretation = interpretation; },
  };
  return { store, state };
}

test("the two refusals: a chapter that is not a lens chapter of this report, and an index outside its two", () => {
  assert.throws(() => checkSceneRequest(report, "twoCharts", 0), (e: Error) => e instanceof SceneRequestError && e.status === 400 && /not a lens chapter/.test(e.message));
  assert.throws(() => checkSceneRequest(report, "people02", 0), /not a lens chapter of this report/);
  assert.throws(() => checkSceneRequest(report, "whatToPractise", 1), /not a lens chapter/);
  const written = report.scenes.partners02.written;
  assert.throws(() => checkSceneRequest(report, "partners02", written), /not one of this chapter's two unread scenes/);
  assert.throws(() => checkSceneRequest(report, "partners02", 3), /two unread scenes/);
  assert.throws(() => checkSceneRequest(report, "partners02", -1), /two unread scenes/);
  const other = [0, 1, 2].find((i) => i !== written)!;
  assert.deepEqual(checkSceneRequest(report, "partners02", other), { titles: report.scenes.partners02.titles, written, stored: null });
});

test("a scene is written once by MODELS.scenes on the chapter's brief, stored, and served from storage after", async () => {
  const { store, state } = memoryStore(report);
  const written = report.scenes.partners03.written;
  const index = [0, 1, 2].find((i) => i !== written)!;
  const title = report.scenes.partners03.titles[index];
  const text = `Marie comes in from the lab and says nothing. Oprah has the plan on the table. "We said Thursday," Oprah says. Marie nods and reads it twice.`;
  let seen = "";
  const reply = (req: FakeRequest) => { seen = req.messages[1].content; return { scene: text }; };
  fake.replies = { ...fake.replies, pair_partners03_scene0: reply, pair_partners03_scene1: reply, pair_partners03_scene2: reply };
  fake.calls = [];
  const out = await writeScene("r1", "partners03", index, store);
  assert.deepEqual(out, { chapter: "partners03", index, text });
  assert.equal(fake.calls.length, 1);
  assert.equal(fake.calls[0], `pair_partners03_scene${index}`);
  assert.match(seen, /THIS CHAPTER'S LINKS/, "the same chapter brief");
  assert.match(seen, new RegExp(`Write scene ${index + 1} of this chapter, "${title.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}"`));
  assert.equal(state.saves, 1);
  assert.equal(state.interpretation.scenes.partners03.texts[String(index)], text);
  assert.equal(state.interpretation.scenes.partners03.written, written, "the written index does not move");
  const usage = state.interpretation.meta.usage;
  assert.equal(usage.sections.length, report.meta.usage.sections.length + 1);
  assert.equal(usage.sections[usage.sections.length - 1].model, MODELS.scenes);
  assert.equal(usage.sections[usage.sections.length - 1].section, "pair:partners03:scene" + index);

  // The second tap is served from storage: no call, no save.
  fake.calls = [];
  const again = await writeScene("r1", "partners03", index, store);
  assert.deepEqual(again, out);
  assert.equal(fake.calls.length, 0);
  assert.equal(state.saves, 1);
});

test("a scene that names only one of the two is logged and stored, never retried (annex row 27)", async () => {
  const { store, state } = memoryStore(report);
  const index = [0, 1, 2].find((i) => i !== report.scenes.partners04.written)!;
  fake.replies = { ...fake.replies, [`pair_partners04_scene${index}`]: () => ({ scene: "Marie comes in late. The kitchen is dark." }) };
  fake.calls = [];
  const out = await writeScene("r1", "partners04", index, store);
  assert.equal(fake.calls.length, 1);
  assert.match(out.text, /kitchen is dark/);
  assert.equal(state.saves, 1);
});

test("a scene that writes a trine is rejected and retried, never stored (annex row 21)", async () => {
  const { store, state } = memoryStore(report);
  const index = [0, 1, 2].find((i) => i !== report.scenes.partners04.written)!;
  let n = 0;
  fake.replies = { ...fake.replies, [`pair_partners04_scene${index}`]: () => ({ scene: n++ === 0 ? "Marie comes in late. Oprah trusts the trine." : "Marie comes in late. Oprah has already eaten." }) };
  fake.calls = [];
  const out = await writeScene("r1", "partners04", index, store);
  assert.equal(fake.calls.length, 2);
  assert.match(out.text, /already eaten/);
  assert.equal(state.saves, 1);
});
